### ISSUE TITLE
Request: Full `One Dark` support

### ISSUE THREAD

**Issue by shadedesignz** [SeanJM/dalton-syntax#1]
Firstly, let me start off by saying I am aware this syntax is not even a day old. Also I think the syntax is quite **beautiful**. Reminds me of the `Rain` syntax.

On install I notice, it does not fully support all that `One Dark` supports (In my case, I am noticing no syntax for JSDocs).

It would be a nice add-in. :]

Other than that, **nice job**!

**Comment by SeanJM** [comment]
So far support is for JS, CSS, SASS, LESS and HTML. If you send me a file with JSDocs I can add support for it.

Thank you for your positive feedback. :)

**Comment by SeanJM** [comment]
Added support for JSDoc

**Comment by shadedesignz** [comment]
Sorry for not getting back to you, but as you have already fixed it, I guess my help wasn't needed. Hah.

It looks good, nice job!

**Comment by SeanJM** [comment]
You're welcome, :) -- and thank you for liking it. It makes it worth doing.
