### ISSUE TITLE
Highlight Line working incorrectly

### ISSUE THREAD

**Issue by haveanicedavid** [SeanJM/dalton-syntax#2]
I love this theme, but right now the highlight line is working incorrectly for me while in a split-pane view. 

It highlights the line on whichever pane i'm *inactive* in (see attached: My active pane is the one on the right)
![screenshot 2016-11-16 15 32 13](https://cloud.githubusercontent.com/assets/9052511/20368626/152afd58-ac12-11e6-9b00-ad81b1cd6d2f.png)

**Comment by SeanJM** [comment]
I'm actually still working on it, currently I removed line highlighting, O_O. But! Since you are the only one to even comment on the theme, your opinion is obviously important! ;)

Do you prefer the line be highlighted?

**Comment by haveanicedavid** [comment]
I actually made a workaround through an [atom package](https://atom.io/packages/highlight-line) and added some custom styling to have it highlighted (er, lowlighted) the way I prefer. I actually kind of like the way it's working now, because I can easily see my previous location on my inactive pane (see attached - active is on left)

Great work with this man - i've tried countless themes and this is definitely one of the most pleasing i've seen.
<img width="930" alt="screenshot 2016-11-17 00 10 25" src="https://cloud.githubusercontent.com/assets/9052511/20379683/c8337bc6-ac5a-11e6-8fea-58c4fa51d966.png">

**Comment by SeanJM** [comment]
Very nice.
